# Personal account related installs
---
- hosts: local
  tasks:

#
# Check out my repos
#

  - name: OrgDocuments repo
    tags:
      - repos
    ansible.builtin.git:
      repo: git@github.com:bradydonald/personal.git
      dest: /home/d/OrgDocuments/personal
      key_file: /home/d/.ssh/ansible_rsa

  - name: .emacs repo
    tags:
      - repos
    ansible.builtin.git:
      repo: git@github.com:bradydonald/.emacs.d.git
      dest: /home/d/.emacs.d
      key_file: /home/d/.ssh/ansible_rsa

  - name: dotfiles repo
    tags:
      - repos
    ansible.builtin.git:
      repo: git@github.com:bradydonald/dotfiles.git
      dest: /home/d/src/dotfiles
      key_file: /home/d/.ssh/ansible_rsa


#
# Fonts
#

  - name: ensure fonts directory
    tags:
      - fonts
    file:
      path: "{{ lookup('env', 'HOME') }}/.fonts"
      state: directory

  - name: Download Hack
    tags:
      - fonts
    ansible.builtin.unarchive:
      src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
      dest: "{{ lookup('env', 'HOME') }}/.fonts/"
      remote_src: yes

  - name: Jetbrain Mono
    tags:
      - fonts
    ansible.builtin.unarchive:
      src: https://download.jetbrains.com/fonts/JetBrainsMono-2.242.zip
      dest: "{{ lookup('env', 'HOME') }}/.fonts/"
      remote_src: yes


  - name: Iosevka Aile
    tags:
      - fonts
    ansible.builtin.unarchive:
      src: https://github.com/be5invis/Iosevka/releases/download/v15.5.2/super-ttc-iosevka-aile-15.5.2.zip
      dest: "{{ lookup('env', 'HOME') }}/.fonts/"
      remote_src: yes


#
# Set up symlinks to dot files
#

  - name: symlink files
    ansible.builtin.shell:
      cmd: sh /home/d/src/dotfiles/add-links.sh
      ignore_errors: yes


#
# Build latest emacs
#

  - name: Checkout Emacs src
    tags:
      - emacs
    ansible.builtin.git:
      repo: https://git.savannah.gnu.org/git/emacs.git
      dest: /home/d/src/emacs

  - name: Build latest emacs
    tags:
      - emacs
    ansible.builtin.shell:
      cmd: sh autogen.sh
      chdir: /home/d/src/emacs
      creates: /home/d/src/emacs/configure

  - name: Build latest emacs
    tags:
      - emacs
    ansible.builtin.shell:
      cmd: ./configure --with-native-compilation --with-gnutls --with-jpeg --with-png --with-rsvg --with-tiff --with-wide-int --with-xft --with-xml2 --with-xpm --without-dbus --without-pop
      chdir: /home/d/src/emacs
      creates: /home/d/src/emacs/Makefile

  - name: Build latest emacs
    tags:
      - emacs
    ansible.builtin.shell:
      cmd: make
      chdir: /home/d/src/emacs

