# Personal account related installs
---
- hosts: local
  tasks:

  - name: ensure src directory
    file:
      path: "{{ lookup('env', 'HOME') }}/src"
      state: directory
    
#
# Check out my repos
#

  - name: OrgDocuments repo
    tags:
      - repos
    ansible.builtin.git:
      repo: git@github.com:bradydonald/personal.git
      dest: /home/d/OrgDocuments/personal
      key_file: /home/d/.ssh/ansible_rsa

  - name: .emacs repo
    tags:
      - repos
    ansible.builtin.git:
      repo: git@github.com:bradydonald/.emacs.d.git
      dest: /home/d/.emacs.d
      key_file: /home/d/.ssh/ansible_rsa

  - name: dotfiles repo
    tags:
      - repos
    ansible.builtin.git:
      repo: git@github.com:bradydonald/dotfiles.git
      dest: /home/d/src/dotfiles
      key_file: /home/d/.ssh/ansible_rsa


#
# Fonts
#

  - name: ensure fonts directory
    tags:
      - fonts
    file:
      path: "{{ lookup('env', 'HOME') }}/.fonts"
      state: directory

  - name: Download Hack
    tags:
      - fonts
    ansible.builtin.unarchive:
      src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
      dest: "{{ lookup('env', 'HOME') }}/.fonts/"
      remote_src: yes

  - name: Jetbrain Mono
    tags:
      - fonts
    ansible.builtin.unarchive:
      src: https://download.jetbrains.com/fonts/JetBrainsMono-2.242.zip
      dest: "{{ lookup('env', 'HOME') }}/.fonts/"
      remote_src: yes


  - name: Iosevka Aile
    tags:
      - fonts
    ansible.builtin.unarchive:
      src: https://github.com/be5invis/Iosevka/releases/download/v15.5.2/super-ttc-iosevka-aile-15.5.2.zip
      dest: "{{ lookup('env', 'HOME') }}/.fonts/"
      remote_src: yes


#
# Set up symlinks to dot files
#

  - name: symlink files
    ansible.builtin.shell:
      cmd: sh /home/d/src/dotfiles/add-links.sh
      ignore_errors: yes

#
# Other misc applications (--tags "bin")
#

  - name: ensure bin directory
    tags:
      - bin
    file:
      path: "{{ lookup('env', 'HOME') }}/bin"
      state: directory

  - name: ensure tmp directory
    tags:
      - bin
    file:
      path: "{{ lookup('env', 'HOME') }}/tmp"
      state: directory

# Install pCloudDrive

  - name: Get pcloud
    tags:
      - bin
    ansible.builtin.get_url:
      url: https://p-def8.pcloud.com/cBZu1eKrMZMqwjTqZZZ6hdtr7Z2ZZil5ZkZPF7pVZrHZrzZBpZpRZc5Z6pZopZ9pZApZGFZUJZkJZPpZkzZWTVkVZnh2ytnYRkjFhQiUzCs40XpaK5xBk/pcloud
      dest: "{{ lookup('env', 'HOME') }}/bin/"
      mode: '755'


#  Install PDFStudio
  - name: Get PDF Studio Pro
    tags:
      - bin
    ansible.builtin.get_url:
      url: https://download.qoppa.com/pdfstudio/PDFStudio_linux64.sh
      dest: "{{ lookup('env', 'HOME') }}/tmp/"
      mode: '755'

  - name: ensure pdfstudio directory
    tags:
      - bin
    file:
      path: "{{ lookup('env', 'HOME') }}/bin/pdfStudioPro"
      state: directory

  - name: Install PDF Studio Pro
    tags:
      - bin
    ansible.builtin.shell:
      cmd: ./PDFStudio_linux64.sh -q -dir "{{ lookup('env', 'HOME') }}/bin/pdfStudioPro"
    args:
      chdir: "{{ lookup('env', 'HOME') }}/tmp/"
