# Personal account related installs
---
- hosts: local
  tasks:

#
# Check out my repos
#

  - name: OrgDocuments repo
    ansible.builtin.git:
      repo: git@github.com:bradydonald/personal.git
      dest: /home/d/OrgDocuments/personal
      key_file: /home/d/.ssh/ansible_rsa

  - name: .emacs repo
    ansible.builtin.git:
      repo: git@github.com:bradydonald/.emacs.d.git
      dest: /home/d/.emacs.d
      key_file: /home/d/.ssh/ansible_rsa

  - name: dotfiles repo
    ansible.builtin.git:
      repo: git@github.com:bradydonald/dotfiles.git
      dest: /home/d/src/dotfiles
      key_file: /home/d/.ssh/ansible_rsa


#
# Fonts
#

  - name: ensure fonts directory
    file:
      path: "{{ lookup('env', 'HOME') }}/.fonts"
      state: directory

  - name: Download Hack
    ansible.builtin.unarchive:
      src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
      dest: "{{ lookup('env', 'HOME') }}/.fonts/"
      remote_src: yes

  - name: Jetbrain Mono
    ansible.builtin.unarchive:
      src: https://download.jetbrains.com/fonts/JetBrainsMono-2.242.zip
      dest: "{{ lookup('env', 'HOME') }}/.fonts/"
      remote_src: yes


  - name: Iosevka Aile
    ansible.builtin.unarchive:
      src: https://github.com/be5invis/Iosevka/releases/download/v15.5.2/super-ttc-iosevka-aile-15.5.2.zip
      dest: "{{ lookup('env', 'HOME') }}/.fonts/"
      remote_src: yes


#
# Build latest emacs
#
  - name: latest emacs
    ansible.builtin.git:
      repo: git clone https://git.savannah.gnu.org/git/emacs.git
      dest: /home/d/src/emacs


#
# Set up symlinks to dot files
#

  - name: symlink files
    ansible.builtin.shell:
      cmd: sh /home/d/src/dotfiles/add-links.sh
      ignore_errors: yes
      
