# Personal account related installs
---
- hosts: local
  tasks:

#
# Check out my repos
#

  - name: OrgDocuments repo
    ansible.builtin.git:
      repo: git@github.com:bradydonald/personal.git
      dest: /home/d/OrgDocuments/personal
      key_file: /home/d/.ssh/ansible_rsa

  - name: .emacs repo
    ansible.builtin.git:
      repo: git@github.com:bradydonald/.emacs.d.git
      dest: /home/d/.emacs.d
      key_file: /home/d/.ssh/ansible_rsa

  - name: dotfiles repo
    ansible.builtin.git:
      repo: git@github.com:bradydonald/dotfiles.git
      dest: /home/d/src/dotfiles
      key_file: /home/d/.ssh/ansible_rsa

  - name: symlink files
    ansible.builtin.shell:
      cmd: sh /home/d/src/dotfiles/add-links.sh
      
