# Personal account related installs
# run with:
#
# runthe entire playbook:
#
# ansible-pull -v -U git@github.com:bradydonald/ansible.git d-user.yml
#
# or just a tag, e.g. repos
#
#  ansible-pull -v -t repos -U git@github.com:bradydonald/ansible.git d-user.yml
#

---
- hosts: localhost
  tasks:

  - name: ensure src directory
    file:
      path: "{{ lookup('env', 'HOME') }}/src"
      state: directory
    
#
# Check out my repos
#

  - name: OrgDocuments repo
    tags:
      - repos
    ansible.builtin.git:
      repo: git@github.com:bradydonald/personal.git
      dest: /home/d/OrgDocuments/personal
      key_file: /home/d/.ssh/id_rsa

  - name: .emacs repo
    tags:
      - repos
    ansible.builtin.git:
      repo: git@github.com:bradydonald/.emacs.d.git
      dest: /home/d/.emacs.d
      key_file: /home/d/.ssh/id_rsa

  - name: dotfiles repo
    tags:
      - repos
    ansible.builtin.git:
      repo: git@github.com:bradydonald/dotfiles.git
      dest: /home/d/src/dotfiles
      key_file: /home/d/.ssh/id_rsa


#
# Fonts
#

  - name: ensure fonts directory
    tags:
      - fonts
    file:
      path: "{{ lookup('env', 'HOME') }}/.fonts"
      state: directory

  - name: Download Hack
    tags:
      - fonts
    ansible.builtin.unarchive:
      src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
      dest: "{{ lookup('env', 'HOME') }}/.fonts/"
      remote_src: yes

  - name: Jetbrain Mono
    tags:
      - fonts
    ansible.builtin.unarchive:
      src: https://download.jetbrains.com/fonts/JetBrainsMono-2.242.zip
      dest: "{{ lookup('env', 'HOME') }}/.fonts/"
      remote_src: yes


  - name: Iosevka Aile
    tags:
      - fonts
    ansible.builtin.unarchive:
      src: https://github.com/be5invis/Iosevka/releases/download/v15.5.2/super-ttc-iosevka-aile-15.5.2.zip
      dest: "{{ lookup('env', 'HOME') }}/.fonts/"
      remote_src: yes

#
# Other misc applications (--tags "bin")
#

  - name: ensure bin directory
    tags:
      - bin
    file:
      path: "{{ lookup('env', 'HOME') }}/bin"
      state: directory

  - name: ensure tmp directory
    tags:
      - bin
    file:
      path: "{{ lookup('env', 'HOME') }}/tmp"
      state: directory


#
# Set up symlinks to dot files
#

  - name: symlink files
    tags:
      - symlinks
    ansible.builtin.shell:
      cmd: sh /home/d/src/dotfiles/add-links.sh

