#
# ansible playbook for consistent install of fedora workstation
#
# run with:
#
# sudo ansible-playbook -i hosts.ini -u root --private-key ~/.ssh/ansible_rsa
# ~/src/ansible/fedora-workstation.yml (optional --tags "zoom")
#

---
- hosts: localhost
  tasks:

# change hostname
# sudo hostnamectl set-hostname "New_Custom_Name"

# install rpm fusion

  - name: Enable rpm fusion free
    ansible.builtin.dnf:
      name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
      state: present
      disable_gpg_check: yes
    tags:
      - repos

  - name: Enable rpm fusion non-free
    ansible.builtin.dnf:
      name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
      disable_gpg_check: yes
      state: present
    tags:
      - repos

  - name: Install full flatpack access
    ansible.builtin.shell:
      cmd: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    tags:
      - repos


# upgrade everything

  - name: Upgrade all packages
    tags:
      - upgrade
    ansible.builtin.dnf:
      name: "*"
      state: latest

# make sure dev tooling is installed

  - name: Install the 'Development tools' package group
    ansible.builtin.dnf:
      name: '@Development tools'
      state: present

# X development tools
# Don't think this is needed on Wayland but this VM is X
#

#
# install 1password repo
#

# install the repo
  - name: Get the 1password key
    tags:
      - 1password
    ansible.builtin.rpm_key:
      state: present
      key: https://downloads.1password.com/linux/keys/1password.asc

  - name: Install the 1password repo
    ansible.builtin.shell:
      cmd:  sudo sh -c 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=\"https://downloads.1password.com/linux/keys/1password.asc\"" > /etc/yum.repos.d/1password.repo'


  - name: Install list of packages
    tags:
      - packages
    ansible.builtin.dnf:
      name: '{{ item }}'
      state: latest
    with_items:
      1password,
      lsd,
      msmtp,
      isync,
      ripgrep,
      sqlite,
      autoconf,
      texinfo,
      libgccjit,
      libgccjit-devel,
      gnutls-devel,
      gnutls,
      gtk4-devel,
      gtk+-devel,
      libXaw-devel,
      libtiff-devel,
      giflib-devel,
      ncurses-devel,
      gnome-tweaks,
      gnome-extensions-app,
      vlc,
      maildir-utils,
      ImageMagick,
      dconf-editor,
      cmake,
      g++,
      cargo,
      meson,
      scdoc,
      neofetch,
      gnuplot,
      qt-devel,
      sway,
      alacritty,
      wshowkeys,
      light,
      clipman,
      mako,
      waybar,
      go,
      xdotool,
      scrot,
      fntsample,
      djvulibre
      
# Install zoom
  - name: Get Zoom 
    tags:
      - zoom
    ansible.builtin.get_url:
      url: https://zoom.us/client/latest/zoom_x86_64.rpm
      dest: "/tmp/"

  - name: Install Zoom
    tags:
      - zoom
    ansible.builtin.dnf:
      name: "/tmp/zoom_x86_64.rpm"
      state: present
      disable_gpg_check: yes

# install teams
  - name: Get Teams
    tags:
      - teams
    ansible.builtin.get_url:
      url: https://packages.microsoft.com/yumrepos/ms-teams/teams-1.5.00.10453-1.x86_64.rpm
      dest: "/tmp/"

  - name: Install Teams
    tags:
      - teams
    ansible.builtin.dnf:
      name: "/tmp/teams-1.5.00.10453-1.x86_64.rpm"
      state: present
      disable_gpg_check: yes

  - name: Enable bridged networking for Boxes
    tags:
      - bridgednw
    ansible.builtin.systemd:
      name: virtnetworkd-ro.socket
      enabled: yes
