#
# ansible playbook for consistent install of fedora workstation
#
# run with:
#
# sudo ansible-pull
#

---
- hosts: localhost
  connection: local
  become: true

  tasks:

  - name: Install list of packages
    tags:
      - packages
    ansible.builtin.dnf:
      name: '{{ item }}'
      state: latest
    with_items:
      msmtp,
      ripgrep,
      sqlite,
      autoconf,
      texinfo,
      libgccjit,
      libgccjit-devel,
      gnutls-devel,
      gnutls,
      gtk4-devel,
      gtk+-devel,
      libXaw-devel,
      libtiff-devel,
      giflib-devel,
      ncurses-devel,
      maildir-utils,
      ImageMagick,
      dconf-editor,
      cmake,
      g++,
      cargo,
      meson,
      scdoc,
      neofetch,
      gnuplot,
      qt-devel,
      go,
      djvulibre,
      mupdf,
      jansson-devel-2.13.1-6.fc38.x86_64
