#
# ansible playbook for consistent install of fedora workstation
#
# run with:
#
# sudo ansible-pull
#
# or
#
# sudo ansible-pull -v -t repos -U git@github.com:bradydonald/ansible.git
#
# will run verbose, executing tag repos
#

---
- hosts: localhost
  connection: local
  become: true

  tasks:

#    
# these rules are for additional repositories
#

  - name: Enable rpm fusion free
    ansible.builtin.dnf:
      name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
      state: present
      disable_gpg_check: yes
    tags:
      - repos

  - name: Enable rpm fusion non-free
    ansible.builtin.dnf:
      name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
      disable_gpg_check: yes
      state: present
    tags:
      - repos

  - name: Install full flatpack access
    ansible.builtin.shell:
      cmd: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    tags:
      - repos


#      
# upgrade everything
#

  - name: Upgrade all packages
    tags:
      - upgrade
    ansible.builtin.dnf:
      name: "*"
      state: latest

#      
# make sure dev tooling is installed
#

  - name: Install the 'Development tools' package group
    ansible.builtin.dnf:
      name: '@Development tools'
      state: present


#
# a whole nunch of packages
#
      
  - name: Install list of packages
    tags:
      - packages
    ansible.builtin.dnf:
      name: '{{ item }}'
      state: latest
    with_items:
      msmtp,
      ripgrep,
      sqlite,
      autoconf,
      texinfo,
      libgccjit,
      libgccjit-devel,
      gnutls-devel,
      gnutls,
      gtk4-devel,
      gtk+-devel,
      libXaw-devel,
      libtiff-devel,
      giflib-devel,
      ncurses-devel,
      maildir-utils,
      cmake,
      g++,
      cargo,
      meson,
      scdoc,
      neofetch,
      gnuplot,
      qt-devel,
      go,
      jansson-devel-2.13.1-6.fc38.x86_64
