#
# ansible playbook for consistent install of fedora workstation
#
# run with:
#
# sudo ansible-pull
#
# or
#
# sudo ansible-pull -v -t repos -U git@github.com:bradydonald/ansible.git
#
# will run verbose, executing tag repos
#

---
- hosts: localhost
  connection: local
  become: true

  tasks:

#    
# these rules are for additional repositories
#

  - name: Enable rpm fusion free
    ansible.builtin.dnf:
      name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
      state: present
      disable_gpg_check: yes
    tags:
      - repos

  - name: Enable rpm fusion non-free
    ansible.builtin.dnf:
      name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
      disable_gpg_check: yes
      state: present
    tags:
      - repos

  - name: Enable wslutilities
    community.general.copr:
      host: copr.fedorainfracloud.org
      state: enabled
      name: wslutilities/wslu
    tags:
      - repos

#      
# upgrade everything
#

  - name: Upgrade all packages
    tags:
      - upgrade
    ansible.builtin.dnf:
      name: "*"
      state: latest

#      
# make sure dev tooling is installed
#

  - name: Install the 'Development tools' package group
    ansible.builtin.dnf:
      name: '@Development tools'
      state: present

  - name: Install the 'Development libraries' package group
    ansible.builtin.dnf:
      name: '@Development Libraries'
      state: present
      
  - name: Install the 'X Development tools' package group
    ansible.builtin.dnf:
      name: '@X Software Development'
      state: present
      

#
# a whole nunch of packages
#
      
  - name: Install list of packages
    tags:
      - packages
    ansible.builtin.dnf:
      name: '{{ item }}'
      state: latest
    with_items:
      aspell,
      aspell-en,
      autoconf,
      cairo-devel,
      cargo,
      cmake,
      g++,
      giflib-devel,
      gnuplot,
      gnutls,
      gnutls-devel,
      go,
      gtk+-devel,
      gtk4-devel,
      jansson-devel-2.13.1-6.fc38.x86_64,
      libXaw-devel,
      libgccjit,
      libgccjit-devel,
      libtiff-devel,
      lsd,
      maildir-utils,
      meson,
      msmtp,
      ncurses-devel,
      neofetch,
      qt-devel,
      ripgrep,
      scdoc,
      sqlite,
      texinfo,
      texlive-scheme-full,
      wslu,
      mpv,
      gtk3-devel.x86_64,
      libsqlite3x-devel,
      enchant2-devel,
      rpmconf,
      rofi,
      inkscape,
      zeal,
      libtree-sitter-devel,
      zsh


  - name: Install youtub-dl
    tags:
      - packages
    ansible.builtin.shell:
      cmd: |
        curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
        chmod a+rx /usr/local/bin/youtube-dl
