# just a starting point for now
---
- hosts: local
  tasks:

# change hostname
# sudo hostnamectl set-hostname "New_Custom_Name"

# install rpm fusion

  - name: Install rpm fusion free
    ansible.builtin.yum_repository:
      name: rpm-fusion-free
      description: RPM Fusion Free Repo
      tags:
        - repos
      baseurl: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$releasever.noarch.rpm

  - name: Install rpm fusion non-free
    ansible.builtin.yum_repository:
      name: rpm-fusion-non-free
      description: RPM Fusion Non-Free Repo
      tags:
        - repos
      baseurl: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$releasever.noarch.rpm

  - name: Install full flatpack access
    ansible.builtin.shell:
      tags:
        - repos
      cmd: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo


# upgrade everything

  - name: Upgrade all packages
    tags:
      - upgrade
    ansible.builtin.dnf:
      name: "*"
      state: latest

# make sure dev tooling is installed

  - name: Install the 'Development tools' package group
    ansible.builtin.dnf:
      name: '@Development tools'
      state: present

# X development tools
# Don't think this is needed on Wayland but this VM is X
#
  - name: Install the 'X Software Development' package group
    ansible.builtin.dnf:
      name: '@X Software Development'
      state: present

#
# install 1password
#

# install the repo
  - name: Get the 1password key
    ansible.builtin.rpm_key:
      state: present
      key: https://downloads.1password.com/linux/keys/1password.asc

  - name: Install the 1password repo
    ansible.builtin.shell:
      cmd:  sudo sh -c 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=\"https://downloads.1password.com/linux/keys/1password.asc\"" > /etc/yum.repos.d/1password.repo'


  - name: Install list of packages
    tags:
      - packages
    ansible.builtin.dnf:
      name: '{{ item }}'
      state: latest
    with_items:
      1password,
      lsd,
      msmtp,
      isync,
      ripgrep,
      sqlite,
      autoconf,
      texinfo,
      libgccjit,
      libgccjit-devel,
      gnutls-devel,
      gnutls,
      gtk4-devel,
      gtk+-devel,
      libXaw-devel,
      libtiff-devel,
      giflib-devel,
      ncurses-devel,
      texlive-scheme-full,
      texstudio,
      gnome-tweaks,
      gnome-extensions-app,
      vlc
      
      
