# just a starting point for now
---
- hosts: local
  tasks:

  - name: Upgrade all packages
    ansible.builtin.dnf:
      name: "*"
      state: latest

  - name: Install the 'Development tools' package group
    ansible.builtin.dnf:
      name: '@Development tools'
      state: present

  - hosts: localhost
    vars:
    roles:
       - agoloncser.emacs
       
