# just a starting point for now
---
- hosts: local
  tasks:

# upgrade everything

  - name: Upgrade all packages
    ansible.builtin.dnf:
      name: "*"
      state: latest

# make sure dev tooling is installed

  - name: Install the 'Development tools' package group
    ansible.builtin.dnf:
      name: '@Development tools'
      state: present

# ansible-galaxy install agoloncser.emacs

  - name: Install emacs
    include_role:
      name: agoloncser.emacs

#
# install 1password
#

# install the repo
  - name: Get the 1password key
    ansible.builtin.rpm_key:
      state: present
      key: https://downloads.1password.com/linux/keys/1password.asc

  - name: Install the repo
    ansible.builtin.shell:
      cmd:  sudo sh -c 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=\"https://downloads.1password.com/linux/keys/1password.asc\"" > /etc/yum.repos.d/1password.repo'

  - name: Install latest
    ansible.builtin.dnf:
      name: "1password"
      state: latest

# lsd command, a more visually appealing ls

  - name: Install lsd command
    ansible.builtin.dnf:
      name: lsd 
      state: latest

# msmtp

  - name: Install msmtp
    ansible.builtin.dnf:
      name: msmtp
      state: latest


# mbsync

  - name: Install mbsync
    ansible.builtin.dnf:
      name: isync
      state: latest
