# install teams
  - name: Get Teams
    tags:
      - teams
    ansible.builtin.get_url:
      url: https://packages.microsoft.com/yumrepos/ms-teams/teams-1.5.00.104
      dest: "/tmp/"

  - name: Install Teams
    tags:
      - teams
    ansible.builtin.dnf:
      name: "/tmp/teams-1.5.00.10453-1.x86_64.rpm"
      state: present
      disable_gpg_check: yes



[Teams]
name=teams
baseurl=https://packages.microsoft.com/yumrepos/ms-teams
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc

dnf config-manager addrepo --from-repofile=/tmp/fedora_extras.repo

