#
# ansible playbook for consistent install of fedora workstation
#
# run with:
#
# sudo ansible-pull
#

---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install htop
    package:
      name: htop

